// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// drawer.js
export const SET_DRAWER = 'SET_DRAWER'

// observations
export const FETCH_SPECIE_OBSERVATIONS_SUCCESS = 'FETCH_SPECIE_OBSERVATIONS_SUCCESS'
export const FETCH_MAP_OBSERVATIONS_SUCCESS = 'FETCH_MAP_OBSERVATIONS_SUCCESS'
export const UPDATE_FILTER_PERIOD_SUCCESS = 'UPDATE_FILTER_PERIOD_SUCCESS'
